// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: A_Lexico.jflex

package com.zafkiel.practica001.analizadores;
import java_cup.runtime.*;
import java.util.List;
import java.util.ArrayList;

@SuppressWarnings("fallthrough")
public class Analizador_Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  2,  3,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     4,  0,  5,  6,  0,  0,  0,  0,  7,  8,  9, 10, 11, 12, 13, 14, 
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15,  0,  0,  0, 16,  0,  0, 
     0, 17, 18, 18, 19, 20, 21, 18, 18, 22, 18, 18, 23, 24, 25, 26, 
    27, 18, 28, 29, 30, 18, 18, 18, 18, 18, 18,  0,  0,  0, 31, 32, 
     0, 17, 18, 18, 19, 20, 21, 18, 18, 22, 18, 18, 23, 24, 25, 26, 
    27, 18, 28, 29, 30, 18, 18, 18, 18, 18, 18,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\4\16"+
    "\1\17\1\20\1\0\1\21\1\22\3\0\1\23\1\0"+
    "\4\20\2\22\1\0\1\24\2\0\2\23\1\25\1\26"+
    "\4\20\3\0\2\25\1\20\1\27\2\20\1\0\1\30"+
    "\1\0\1\20\1\31\1\20\2\0\2\20\1\32\1\0"+
    "\1\20\1\0\1\20\1\33\21\0\1\34\3\0\1\35";

  private static int [] zzUnpackAction() {
    int [] result = new int[95];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\41\0\41\0\102\0\143\0\204\0\41\0\41"+
    "\0\245\0\306\0\41\0\41\0\41\0\41\0\347\0\41"+
    "\0\u0108\0\u0129\0\u014a\0\u016b\0\41\0\u0108\0\143\0\41"+
    "\0\u018c\0\u01ad\0\u01ce\0\u01ef\0\u0210\0\u0231\0\u0252\0\u0273"+
    "\0\u0294\0\u02b5\0\41\0\u02d6\0\u02f7\0\41\0\u0318\0\u0339"+
    "\0\41\0\u035a\0\u037b\0\u039c\0\u03bd\0\u03de\0\u03ff\0\u0420"+
    "\0\u0441\0\u0462\0\u0483\0\41\0\u04a4\0\u04c5\0\u0108\0\u04e6"+
    "\0\u0507\0\u0528\0\41\0\u0549\0\u056a\0\u0108\0\u058b\0\u05ac"+
    "\0\u05cd\0\u05ee\0\u060f\0\41\0\u0630\0\u0651\0\u0672\0\u0693"+
    "\0\41\0\u06b4\0\u06d5\0\u06f6\0\u0717\0\u0738\0\u0759\0\u077a"+
    "\0\u079b\0\u07bc\0\u07dd\0\u07fe\0\u081f\0\u0840\0\u0861\0\u0882"+
    "\0\u08a3\0\u08c4\0\41\0\u08e5\0\u0906\0\u0927\0\41";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[95];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\0\1\4\1\3\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\4\21\1\22\5\21\1\23\1\24\2\21\1\25"+
    "\1\26\42\0\1\3\37\0\5\27\1\30\33\27\4\0"+
    "\1\31\1\0\1\32\32\0\1\33\1\0\1\33\1\0"+
    "\5\33\1\34\27\33\4\0\1\35\51\0\1\36\1\0"+
    "\1\17\40\0\1\26\1\0\16\26\1\0\1\26\17\0"+
    "\1\26\1\0\11\26\1\37\4\26\1\0\1\26\17\0"+
    "\1\26\1\0\6\26\1\40\4\26\1\41\2\26\1\0"+
    "\1\26\17\0\1\26\1\0\3\26\1\42\12\26\1\0"+
    "\1\26\1\31\1\43\1\31\1\44\35\31\4\0\1\31"+
    "\1\0\1\45\32\0\1\33\1\0\1\33\1\0\5\33"+
    "\1\46\27\33\1\47\1\0\1\47\1\0\5\47\1\50"+
    "\27\47\1\35\1\51\1\35\1\52\35\35\4\0\1\53"+
    "\12\0\1\54\40\0\1\26\1\0\13\26\1\55\2\26"+
    "\1\0\1\26\17\0\1\26\1\0\11\26\1\56\4\26"+
    "\1\0\1\26\17\0\1\26\1\0\5\26\1\57\10\26"+
    "\1\0\1\26\17\0\1\26\1\0\12\26\1\60\3\26"+
    "\1\0\1\26\1\0\1\43\43\0\1\31\1\0\1\61"+
    "\32\0\1\47\1\0\1\47\1\0\5\47\1\62\27\47"+
    "\1\63\1\0\1\63\1\0\5\63\1\0\27\63\1\0"+
    "\1\51\37\0\1\53\1\64\1\53\1\65\35\53\17\0"+
    "\1\54\40\0\1\26\1\0\7\26\1\66\6\26\1\0"+
    "\1\26\17\0\1\26\1\0\15\26\1\67\1\0\1\26"+
    "\17\0\1\26\1\0\10\26\1\70\5\26\1\0\1\26"+
    "\17\0\1\26\1\0\11\26\1\71\4\26\1\0\1\26"+
    "\4\0\1\31\1\0\1\72\43\0\1\73\27\0\1\63"+
    "\1\0\1\63\1\0\5\63\1\74\27\63\1\0\1\64"+
    "\56\0\1\26\1\0\1\75\15\26\1\0\1\26\17\0"+
    "\1\26\1\0\15\26\1\76\1\0\1\26\17\0\1\26"+
    "\1\0\13\26\1\77\2\26\1\0\1\26\4\0\1\31"+
    "\1\0\1\100\43\0\1\101\46\0\1\26\1\0\15\26"+
    "\1\102\1\0\1\26\17\0\1\26\1\0\15\26\1\103"+
    "\1\0\1\26\4\0\1\31\45\0\1\104\36\0\1\105"+
    "\7\0\1\26\1\0\16\26\1\0\1\26\17\0\1\26"+
    "\1\0\3\26\1\106\12\26\1\0\1\26\10\107\1\0"+
    "\30\107\17\0\1\26\1\0\14\26\1\110\1\26\1\0"+
    "\1\26\10\107\1\111\30\107\15\0\1\112\1\0\1\26"+
    "\1\0\16\26\1\0\1\26\24\0\1\113\5\0\1\114"+
    "\42\0\1\115\37\0\1\116\41\0\1\117\30\0\1\120"+
    "\46\0\1\121\42\0\1\122\40\0\1\123\25\0\1\124"+
    "\43\0\1\125\37\0\1\126\52\0\1\127\35\0\1\130"+
    "\15\0\1\131\65\0\1\132\14\0\1\133\54\0\1\134"+
    "\51\0\1\135\12\0\1\136\41\0\1\137\30\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[2376];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\2\11\2\1\4\11\1\1\1\11"+
    "\4\1\1\11\1\1\1\0\1\11\1\1\3\0\1\1"+
    "\1\0\4\1\1\11\1\1\1\0\1\11\2\0\1\11"+
    "\7\1\3\0\1\11\5\1\1\0\1\11\1\0\3\1"+
    "\2\0\2\1\1\11\1\0\1\1\1\0\1\1\1\11"+
    "\21\0\1\11\3\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[95];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private int counter;
    private int counter2;
    private static List<String> lexicos = new ArrayList<>();
    public static List<String> getLexicos() {
        return lexicos;
    }
    private static List<String> erroresLexicos = new ArrayList<>();
    public static List<String> getErroresLexicos() {
        return erroresLexicos;
    }
    private static List<String> errores = new ArrayList<>();
    public static List<String> getErrores() {
        return errores;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Analizador_Lexico(java.io.Reader in) {
      counter = 0;
    counter2 = 0;
    yyline = 1;
    yycolumn = 1;
    yychar = 1;
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    return ZZ_CMAP[input];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(Simbolo.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { counter++;
    counter2++;
    lexicos.add("---->   ERROR LEXICO: " +counter2+ "                   Contador: "+counter+"                    Lexema: " + yytext() + "                   Keyword: " + "ERROR - Simbolo no existe en el lenguaje" +
                "                   Linea: " + yyline +"                   Columna: " + yycolumn + "                   Caracter: " + yychar+"\n");
    erroresLexicos.add("---->   ERROR LEXICO: " +counter2+ "                    Lexema: " + yytext() + "                   Keyword: " + "ERROR - Simbolo no existe en el lenguaje" +
                "                   Linea: " + yyline +"                   Columna: " + yycolumn + "                   Caracter: " + yychar+"\n");
    errores.add("---->   ERROR LEXICO: " +counter2+ "                    Lexema: " + yytext() + "                   Keyword: " + "ERROR - Simbolo no existe en el lenguaje" +
                "                   Linea: " + yyline +"                   Columna: " + yycolumn + "                   Caracter: " + yychar+"\n");
            }
          // fall through
          case 30: break;
          case 2:
            { 
            }
          // fall through
          case 31: break;
          case 3:
            { counter++;
    lexicos.add( "--->   Contador: "+counter+ "          Token: "+yytext()+"          Tipo: NUMERAL"+".         Linea: " +yyline +"          Columna: "+yycolumn+"          Caracter: "+yychar+"\n");
    return new Symbol(Simbolo.NUMERAL, yycolumn, yyline, yytext());
            }
          // fall through
          case 32: break;
          case 4:
            { counter++;
    lexicos.add( "--->   Contador: "+counter+ "          Token: "+yytext()+"          Tipo: PARENTESIS ABIERTO"+".         Linea: " +yyline +"          Columna: "+yycolumn+"          Caracter: "+yychar+"\n");
   return new Symbol(Simbolo.PARA, yycolumn, yyline, yytext());
            }
          // fall through
          case 33: break;
          case 5:
            { counter++;
    lexicos.add( "--->   Contador: "+counter+ "          Token: "+yytext()+"          Tipo: PARENTESIS CERRADO"+".         Linea: " +yyline +"          Columna: "+yycolumn+"          Caracter: "+yychar+"\n");
    return new Symbol(Simbolo.PARB, yycolumn, yyline, yytext());
            }
          // fall through
          case 34: break;
          case 6:
            { counter++;
    lexicos.add( "--->   Contador: "+counter+ "          Token: "+yytext()+"          Tipo: MULTIPLICACION"+".         Linea: " +yyline +"          Columna: "+yycolumn+"          Caracter: "+yychar+"\n");
    return new Symbol(Simbolo.POR, yycolumn, yyline, yytext());
            }
          // fall through
          case 35: break;
          case 7:
            { counter++;
    lexicos.add( "--->   Contador: "+counter+ "          Token: "+yytext()+"          Tipo: SUMA"+".         Linea: " +yyline +"          Columna: "+yycolumn+"          Caracter: "+yychar+"\n");
    return new Symbol(Simbolo.MAS, yycolumn, yyline, yytext());
            }
          // fall through
          case 36: break;
          case 8:
            { counter++;
    lexicos.add( "--->   Contador: "+counter+ "          Token: "+yytext()+"          Tipo: COMA"+".         Linea: " +yyline +"          Columna: "+yycolumn+"          Caracter: "+yychar+"\n");
    return new Symbol(Simbolo.COMA, yycolumn, yyline, yytext());
            }
          // fall through
          case 37: break;
          case 9:
            { counter++;
    lexicos.add( "--->   Contador: "+counter+ "          Token: "+yytext()+"          Tipo: RESTA"+".         Linea: " +yyline +"          Columna: "+yycolumn+"          Caracter: "+yychar+"\n");
    return new Symbol(Simbolo.MENOS, yycolumn, yyline, yytext());
            }
          // fall through
          case 38: break;
          case 10:
            { counter++;
    lexicos.add( "--->   Contador: "+counter+ "          Token: "+yytext()+"          Tipo: PUNTO"+".         Linea: " +yyline +"          Columna: "+yycolumn+"          Caracter: "+yychar+"\n");
    return new Symbol(Simbolo.PUNTO, yycolumn, yyline, yytext());
            }
          // fall through
          case 39: break;
          case 11:
            { counter++;
    lexicos.add( "--->   Contador: "+counter+ "          Token: "+yytext()+"          Tipo: DIVICION"+".         Linea: " +yyline +"          Columna: "+yycolumn+"          Caracter: "+yychar+"\n");
    return new Symbol(Simbolo.DIV, yycolumn, yyline, yytext());
            }
          // fall through
          case 40: break;
          case 12:
            { counter++;
    lexicos.add( "--->   Contador: "+counter+ "          Token: "+yytext()+"          Tipo: ENTERO"+".         Linea: " +yyline +"          Columna: "+yycolumn+"          Caracter: "+yychar+"\n");
    return new Symbol(Simbolo.ENTERO, yycolumn, yyline, yytext());
            }
          // fall through
          case 41: break;
          case 13:
            { counter++;
    lexicos.add( "--->   Contador: "+counter+ "          Token: "+yytext()+"          Tipo: IGUAL"+".         Linea: " +yyline +"          Columna: "+yycolumn+"          Caracter: "+yychar+"\n");
    return new Symbol(Simbolo.IGUAL, yycolumn, yyline, yytext());
            }
          // fall through
          case 42: break;
          case 14:
            { counter++;
    lexicos.add( "--->   Contador: "+counter+ "          Token: "+yytext()+"          Tipo: CARACTER"+".         Linea: " +yyline +"          Columna: "+yycolumn+"          Caracter: "+yychar+"\n");
    return new Symbol(Simbolo.CARACTER, yycolumn, yyline, yytext());
            }
          // fall through
          case 43: break;
          case 15:
            { counter++;
    lexicos.add( "--->   Contador: "+counter+ "          Token: "+yytext()+"          Tipo: POTENCIA"+".         Linea: " +yyline +"          Columna: "+yycolumn+"          Caracter: "+yychar+"\n");
    return new Symbol(Simbolo.POTENCIA, yycolumn, yyline, yytext());
            }
          // fall through
          case 44: break;
          case 16:
            { counter++;
    lexicos.add( "--->   Contador: "+counter+ "          Token: "+yytext()+"          Tipo: IDENTIFICADOR"+".         Linea: " +yyline +"          Columna: "+yycolumn+"          Caracter: "+yychar+"\n");
    return new Symbol(Simbolo.IDENTIFICADOR, yycolumn, yyline, yytext());
            }
          // fall through
          case 45: break;
          case 17:
            { counter++;
    String cadena = yytext();
    cadena = cadena.substring(1, cadena.length()-1);
    lexicos.add( "--->   Contador: "+counter+ "          Token: "+cadena+"          Tipo: CADENA"+".         Linea: " +yyline +"          Columna: "+yycolumn+"          Caracter: "+yychar+"\n");
    return new Symbol(Simbolo.CADENA, yycolumn, yyline, cadena);
            }
          // fall through
          case 46: break;
          case 18:
            { counter++;
    lexicos.add("---> Contador: "+counter+"          Token: "+yytext()+"          Tipo: INSTRUCCION HEADER.          Línea: "+yyline+"          Columna: "+yycolumn+"\n");
    return new Symbol(Simbolo.HEADER, yycolumn, yyline, yytext());
            }
          // fall through
          case 47: break;
          case 19:
            { counter++;
    lexicos.add("---> Contador: "+counter+"          Token: "+yytext()+"          Tipo: INSTRUCCION TEXTO EN LISTA NO ORDENADA.          Línea: "+yyline+"          Columna: "+yycolumn+"\n");
    return new Symbol(Simbolo.LISTA_NO_ORDENADA, yycolumn, yyline, yytext());
            }
          // fall through
          case 48: break;
          case 20:
            { counter++;
    lexicos.add("---> Contador: "+counter+"          Token: "+yytext()+"          Tipo: INSTRUCCION TEXTO EN ITALICA.          Línea: "+yyline+"          Columna: "+yycolumn+"\n");
    return new Symbol(Simbolo.TEXTO_ITALICA, yycolumn, yyline, yytext());
            }
          // fall through
          case 49: break;
          case 21:
            { counter++;
    lexicos.add("---> Contador: "+counter+"          Token: "+yytext()+"          Tipo: INSTRUCCION TEXTO LISTA ORDENADA.          Línea: "+yyline+"          Columna: "+yycolumn+"\n");
    return new Symbol(Simbolo.LISTA_ORDENADA, yycolumn, yyline, yytext());
            }
          // fall through
          case 50: break;
          case 22:
            { counter++;
    lexicos.add( "--->   Contador: "+counter+ "          Token: "+yytext()+"          Tipo: DECIMAL"+".         Linea: " +yyline +"          Columna: "+yycolumn+"          Caracter: "+yychar+"\n");
    return new Symbol(Simbolo.DECIMAL, yycolumn, yyline, yytext());
            }
          // fall through
          case 51: break;
          case 23:
            { counter++;
    lexicos.add( "--->   Contador: "+counter+ "          Token: "+yytext()+"          Tipo: INSTRUCCION PLOT"+".         Linea: " +yyline +"          Columna: "+yycolumn+"          Caracter: "+yychar+"\n");
    return new Symbol(Simbolo.PLOT, yycolumn, yyline, yytext());
            }
          // fall through
          case 52: break;
          case 24:
            { counter++;
    lexicos.add("---> Contador: "+counter+"          Token: "+yytext()+"          Tipo: INSTRUCCION TEXTO EN NEGRITA.          Línea: "+yyline+"          Columna: "+yycolumn+"\n");
    return new Symbol(Simbolo.TEXTO_NEGRITA, yycolumn, yyline, yytext());
            }
          // fall through
          case 53: break;
          case 25:
            { counter++;
    lexicos.add("---> Contador: "+counter+"          Token: "+yytext()+"          Tipo: PALABRA RESERVADA.          Línea: "+yyline+"          Columna: "+yycolumn+"\n");
    return new Symbol(Simbolo.PRINT, yycolumn, yyline, yytext());
            }
          // fall through
          case 54: break;
          case 26:
            { counter++;
    lexicos.add("---> Contador: "+counter+"          Token: "+yytext()+"          Tipo: INSTRUCCION TEXTO EN NEGRITA E ITALICA.          Línea: "+yyline+"          Columna: "+yycolumn+"\n");
    return new Symbol(Simbolo.TEXTO_NEGRITA_ITALICA, yycolumn, yyline, yytext());
            }
          // fall through
          case 55: break;
          case 27:
            { counter++;
    lexicos.add( "--->   Contador: "+counter+ "          Token: "+yytext()+"          Tipo: INSTRUCCION FORMAT"+".         Linea: " +yyline +"          Columna: "+yycolumn+"          Caracter: "+yychar+"\n");
    return new Symbol(Simbolo.FORMAT, yycolumn, yyline, yytext());
            }
          // fall through
          case 56: break;
          case 28:
            { counter++;
    lexicos.add( "--->   Contador: "+counter+ "          Token: "+yytext()+"          Tipo: REPORTES ERRORES"+".         Linea: " +yyline +"          Columna: "+yycolumn+"          Caracter: "+yychar+"\n");
    return new Symbol(Simbolo.REPORTEERRORES, yycolumn, yyline, yytext());
            }
          // fall through
          case 57: break;
          case 29:
            { counter++;
    lexicos.add( "--->   Contador: "+counter+ "          Token: "+yytext()+"          Tipo: REPORTES OPERADORES"+".         Linea: " +yyline +"          Columna: "+yycolumn+"          Caracter: "+yychar+"\n");
    return new Symbol(Simbolo.REPORTESOPERADORES, yycolumn, yyline, yytext());
            }
          // fall through
          case 58: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
