
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.zafkiel.practica001.analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int TEXTO_ITALICA = 18;
  public static final int PLOT = 23;
  public static final int MENOS = 3;
  public static final int PUNTO = 10;
  public static final int CADENA = 27;
  public static final int LISTA_NO_ORDENADA = 17;
  public static final int IGUAL = 9;
  public static final int TEXTO_NEGRITA = 19;
  public static final int DECIMAL = 25;
  public static final int POTENCIA = 6;
  public static final int PARB = 8;
  public static final int PARA = 7;
  public static final int POR = 4;
  public static final int CARACTER = 28;
  public static final int COMA = 12;
  public static final int REPORTEERRORES = 14;
  public static final int EOF = 0;
  public static final int DIV = 5;
  public static final int PRINT = 21;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 26;
  public static final int HEADER = 15;
  public static final int FORMAT = 22;
  public static final int ENTERO = 24;
  public static final int LISTA_ORDENADA = 16;
  public static final int TEXTO_NEGRITA_ITALICA = 20;
  public static final int REPORTESOPERADORES = 13;
  public static final int NUMERAL = 11;
  public static final int MAS = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "POTENCIA",
  "PARA",
  "PARB",
  "IGUAL",
  "PUNTO",
  "NUMERAL",
  "COMA",
  "REPORTESOPERADORES",
  "REPORTEERRORES",
  "HEADER",
  "LISTA_ORDENADA",
  "LISTA_NO_ORDENADA",
  "TEXTO_ITALICA",
  "TEXTO_NEGRITA",
  "TEXTO_NEGRITA_ITALICA",
  "PRINT",
  "FORMAT",
  "PLOT",
  "ENTERO",
  "DECIMAL",
  "IDENTIFICADOR",
  "CADENA",
  "CARACTER"
  };
}

